# SITE CONFIGURATION
title: Ekin Deniz Aksu # your site title
author: ekinda # You :P
description: > My blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ekinda.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Ekin Deniz Aksu
  links:
  #  - https://twitter.com/BenBalter
  #  - https://www.facebook.com/ben.balter
  #  - https://www.linkedin.com/in/BenBalter
  #  - https://plus.google.com/+BenBalter
  #  - https://github.com/benbalter
  #  - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
  - {name: 'CV', link: '/cv'}

tagline: >
  Page under construction.

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: aksuekin@gmail.com # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
#github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
